<a href="https://colab.research.google.com/github/QuothTheRaven42/learning_files/blob/master/U_of_MI_Data_Science_Coursera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# https://www.coursera.org/learn/python-data-analysis/lecture/LdmXU/advanced-python-demonstration-the-numerical-python-library-numpy

In [1]:
import numpy as np

In [3]:
my_list = [1,2,3,4]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4]


In [4]:
n = np.array([[1,2,3], [4,5,6]])
print(n.shape)

(2, 3)


In [6]:
# evenly spaced integers, works same as range
n = np.arange(0, 30, 2)
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [7]:
# can reshape array
print(n.reshape(3,5))

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [8]:
#similar but returns split by given interval
o = np.linspace(0,4,9)
o.resize(3,3) # resize changes dimensions in place, returns None
print(o)

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


In [9]:
# 1's for all values
print(np.ones((3,2)))
# 0's on diagonal
print(np.zeros((3,2)))
# 1's on diagonal
print(np.eye(3))
# specific array on diagonal
print(np.diag(n))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 12  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 16  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 18  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 22  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 24  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 26  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 28]]


In [10]:
# multiplying repeats entire array
print(np.array([1,2,3] * 3))
# .repeat() broadcasts multiplication by keyword int
print(np.repeat([1,2,3], 3))

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [11]:
p = np.ones([3,3], int) # returns float by default, can change by keyword
print(p)
# stack array in vertical sequence
print(np.vstack([p, 2*p]))
# stack array in horizontal sequence
print(np.hstack([p, 2*p]))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [1 1 1 2 2 2]]


## Operations

In [12]:
print(o + p) # as long as same shape
print(o.dot(p)) # dot product from linear algebra

[[1.  1.5 2. ]
 [2.5 3.  3.5]
 [4.  4.5 5. ]]
[[ 1.5  1.5  1.5]
 [ 6.   6.   6. ]
 [10.5 10.5 10.5]]


In [14]:
x = np.array([o, o**2])
print(x.T) # transpose shape

[[[ 0.    0.  ]
  [ 1.5   2.25]
  [ 3.    9.  ]]

 [[ 0.5   0.25]
  [ 2.    4.  ]
  [ 3.5  12.25]]

 [[ 1.    1.  ]
  [ 2.5   6.25]
  [ 4.   16.  ]]]


In [15]:
print(x.dtype) # check dtype
x = x.astype('i') # can change dtype with .astype()
print(x.dtype) # dtype is changed to int

float64
int32


In [16]:
a = np.array([-4, -2, 1, 3 ,5])
print(a.sum())
print(a.max())
print(a.argmax()) # index of maximum value
print(a.argmin()) # index of minimum value
print(a.std()) # standard deviation of values

3
5
4
0
3.2619012860600183


## Indexing and slicing

In [17]:
z = np.arange(10) ** 2
print(z)
print(z[0], z[4], z[:3]) # slice returns an array
print(z[-4:])

[ 0  1  4  9 16 25 36 49 64 81]
0 16 [0 1 4]
[36 49 64 81]


In [18]:
y = np.arange(36)
y.resize([6,6])
print(y)
print(y[2,2]) # comma notation to access values by row and column
print(y[3,3:6]) # 3rd index row, 3rd through 5th index columns
print(y[-1,::2]) # every other element from last row
print(y[y > 30]) # conditional indexing
y[y > 30] = 30 # conditional assignment

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
14
[21 22 23]
[30 32 34]
[31 32 33 34 35]


In [19]:
y2 = y[:3, :3] # not a copy!
y2[:] = 0
print(y) # assigned to both y and y2
print(y.copy()) # actual copy

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## iterating over arrays

In [20]:
test = np.random.randint(0, 10, (4,3)) # pass in shape as tuple

In [21]:
for row in test:
    print(row)

[7 0 6]
[2 8 2]
[6 7 0]
[4 2 7]


In [22]:
for i in range(len(test)):
    print(test[i])

[7 0 6]
[2 8 2]
[6 7 0]
[4 2 7]


In [23]:
for i, row in enumerate(test):
    print(i, row)

0 [7 0 6]
1 [2 8 2]
2 [6 7 0]
3 [4 2 7]


In [24]:
test2 = test**2
for i, j in zip(test, test2):
    print(f'{i} + {j} = {i+j}')

[7 0 6] + [49  0 36] = [56  0 42]
[2 8 2] + [ 4 64  4] = [ 6 72  6]
[6 7 0] + [36 49  0] = [42 56  0]
[4 2 7] + [16  4 49] = [20  6 56]
